# Use postgres/example user/password credentials
version: "3.9"

services:
  db:
    image: postgres:16
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    volumes:
      - ./docker-data/db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb

    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      # - POSTGRES_DB=testDB
      # - POSTGRES_USER=postgres
      # - POSTGRES_PASSWORD=postgres
    # environment:
    #   POSTGRES_PASSWORD: example

  # Below Adminer is not necessary - you can use prisma studio UI;
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
