import "@radix-ui/themes/styles.css";
// import "./theme-config.css";
import "@/app/theme-config.css";
// import "./globals.css";
import "@/app/globals.css";
import type { Metadata } from "next";
import NavBar from "./NavBar";
import { Container, Theme } from "@radix-ui/themes";
import AuthProvider from "./auth/Provider";
import QueryClientProvider from "./QueryClientProvider";
import { Providers } from "./providers";
import { Toaster } from "react-hot-toast";
import { inter } from "./ui/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.variable}>
        <Providers>
          <QueryClientProvider>
            <AuthProvider>
              <Theme>
                <NavBar />
                <main className="p-5">
                  <Container>
                    <Toaster /> {children}
                  </Container>
                </main>
              </Theme>
            </AuthProvider>
          </QueryClientProvider>
        </Providers>
      </body>
    </html>
  );
}
