import "@radix-ui/themes/styles.css";
// import "./theme-config.css";
import "@/app/styles/theme-config.css";
// import "./globals.css";
import "@/app/styles/globals.css";
import { Theme } from "@radix-ui/themes";
import type { Metadata } from "next";
import NextTopLoader from "nextjs-toploader";
import { Toaster } from "react-hot-toast";
import NavBar from "./NavBar";
import AuthSessionProvider from "./providers/AuthSessionProvider";
import { NextUIComponentsProvider } from "./providers/NextUIComponentsProvider";
import TanSackQueryClientProvider from "./providers/TanSackQueryClientProvider";
import { inter } from "./ui/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="light">
      <body className={inter.variable}>
        <TanSackQueryClientProvider>
          <NextUIComponentsProvider>
            <AuthSessionProvider>
              <Theme>
                <NavBar />
                <main className="mx-auto w-full max-w-[1400px] p-5">
                  {/* <Container> */}
                  <Toaster /> <NextTopLoader /> {children}
                  {/* </Container> */}
                </main>
              </Theme>
            </AuthSessionProvider>
          </NextUIComponentsProvider>
        </TanSackQueryClientProvider>
      </body>
    </html>
  );
}
